services:
  synapse:
    image: ghcr.io/syndrizzle/synapse:latest
    ports:
      - "3000:3000"
    environment:
      - SERVICE_FQDN_SYNAPSE_3000
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${PORT:-3000}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY:-}
      - OPENROUTER_MODEL=${OPENROUTER_MODEL:-google/gemini-2.5-flash}
      - REDIS_URL=${REDIS_URL:-keydb://keydb:6379}
      - MIN_QUIZ_LENGTH=${MIN_QUIZ_LENGTH:-5}
      - MAX_QUIZ_LENGTH=${MAX_QUIZ_LENGTH:-50}
      - ENABLE_RATE_LIMITING=${ENABLE_RATE_LIMITING:-true}
      - RATE_LIMIT_QUIZZES_PER_MINUTE=${RATE_LIMIT_QUIZZES_PER_MINUTE:-2}
      - RATE_LIMIT_API_REQUESTS_PER_MINUTE=${RATE_LIMIT_API_REQUESTS_PER_MINUTE:-50}
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:3000}
      - AUTHORIZED_DOMAINS=${AUTHORIZED_DOMAINS:-http://localhost:3000}
      - MAX_REQUEST_SIZE=${MAX_REQUEST_SIZE:-10485760}
      - MAX_FILES_COUNT=${MAX_FILES_COUNT:-6}
      - DEBUG_MODE=${DEBUG_MODE:-true}
      - TRUST_PROXY=${TRUST_PROXY:-true}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/v1/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 30s

  keydb:
    image: eqalpha/keydb:latest
    command: keydb-server --appendonly yes
    environment:
      - KEYDB_PASSWORD=${SERVICE_PASSWORD_KEYDB}
    volumes:
      - synapse-keydb-data:/data
    healthcheck:
      test: ["CMD-SHELL", "keydb-cli --pass \"${SERVICE_PASSWORD_KEYDB}\" ping"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
