services:
  app:
    image: ghcr.io/syndrizzle/synapse:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${PORT:-3000}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY:-}
      - OPENROUTER_MODEL=${OPENROUTER_MODEL:-google/gemini-2.5-flash}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - MIN_QUIZ_LENGTH=${MIN_QUIZ_LENGTH:-5}
      - MAX_QUIZ_LENGTH=${MAX_QUIZ_LENGTH:-50}
      - ENABLE_RATE_LIMITING=${ENABLE_RATE_LIMITING:-true}
      - GENERAL_RATE_LIMIT_REQUESTS=${GENERAL_RATE_LIMIT_REQUESTS:-12}
      - GENERAL_RATE_LIMIT_WINDOW_MINUTES=${GENERAL_RATE_LIMIT_WINDOW_MINUTES:-1}
      - QUIZ_RATE_LIMIT_REQUESTS=${QUIZ_RATE_LIMIT_REQUESTS:-1}
      - QUIZ_RATE_LIMIT_WINDOW_MINUTES=${QUIZ_RATE_LIMIT_WINDOW_MINUTES:-1}
      - HEALTH_RATE_LIMIT_REQUESTS=${HEALTH_RATE_LIMIT_REQUESTS:-10}
      - HEALTH_RATE_LIMIT_WINDOW_MINUTES=${HEALTH_RATE_LIMIT_WINDOW_MINUTES:-1}
      - AUTHORIZED_RATE_LIMIT_REQUESTS=${AUTHORIZED_RATE_LIMIT_REQUESTS:-50}
      - AUTHORIZED_RATE_LIMIT_WINDOW_MINUTES=${AUTHORIZED_RATE_LIMIT_WINDOW_MINUTES:-1}
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:3000}
      - AUTHORIZED_DOMAINS=${AUTHORIZED_DOMAINS:-http://localhost:3000}
      - MAX_REQUEST_SIZE=${MAX_REQUEST_SIZE:-10485760}
      - MAX_FILES_COUNT=${MAX_FILES_COUNT:-6}
      - DEBUG_MODE=${DEBUG_MODE:-true}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/v1/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 30s
