services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL:-https://synapse-server.drzl.dev}
      - VITE_UPLOAD_TIMEOUT=${VITE_UPLOAD_TIMEOUT:-300000}
      - __VITE_ADDITIONAL_SERVER_ALLOWED_HOSTS=${__VITE_ADDITIONAL_SERVER_ALLOWED_HOSTS:-0.0.0.0}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 30s

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${PORT:-3000}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - OPENROUTER_MODEL=${OPENROUTER_MODEL:-openai/gpt-4.1}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - MIN_QUIZ_LENGTH=${MIN_QUIZ_LENGTH:-5}
      - MAX_QUIZ_LENGTH=${MAX_QUIZ_LENGTH:-50}
      - ENABLE_RATE_LIMITING=${ENABLE_RATE_LIMITING:-true}
      - GENERAL_RATE_LIMIT_REQUESTS=${GENERAL_RATE_LIMIT_REQUESTS:-12}
      - GENERAL_RATE_LIMIT_WINDOW_MINUTES=${GENERAL_RATE_LIMIT_WINDOW_MINUTES:-1}
      - QUIZ_RATE_LIMIT_REQUESTS=${QUIZ_RATE_LIMIT_REQUESTS:-1}
      - QUIZ_RATE_LIMIT_WINDOW_MINUTES=${QUIZ_RATE_LIMIT_WINDOW_MINUTES:-1}
      - HEALTH_RATE_LIMIT_REQUESTS=${HEALTH_RATE_LIMIT_REQUESTS:-10}
      - HEALTH_RATE_LIMIT_WINDOW_MINUTES=${HEALTH_RATE_LIMIT_WINDOW_MINUTES:-1}
      - AUTHORIZED_RATE_LIMIT_REQUESTS=${AUTHORIZED_RATE_LIMIT_REQUESTS:-50}
      - AUTHORIZED_RATE_LIMIT_WINDOW_MINUTES=${AUTHORIZED_RATE_LIMIT_WINDOW_MINUTES:-1}
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:5173,http://localhost:3000}
      - AUTHORIZED_DOMAINS=${AUTHORIZED_DOMAINS:-http://localhost:5173}
      - MAX_REQUEST_SIZE=${MAX_REQUEST_SIZE:-10mb}
      - MAX_FILES_COUNT=${MAX_FILES_COUNT:-7}
      - DEBUG_MODE=${DEBUG_MODE:-true}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 30s
