services:
  synapse:
    image: synapse:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${PORT:-3000}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY:-}
      - TAVILY_API_KEY=${TAVILY_API_KEY:-}
      - OPENROUTER_MODEL=${OPENROUTER_MODEL:-openai/gpt-4.1-mini}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - MIN_QUIZ_LENGTH=${MIN_QUIZ_LENGTH:-5}
      - MAX_QUIZ_LENGTH=${MAX_QUIZ_LENGTH:-50}
      - ENABLE_RATE_LIMITING=${ENABLE_RATE_LIMITING:-true}
      - RATE_LIMIT_QUIZZES_PER_MINUTE=${RATE_LIMIT_QUIZZES_PER_MINUTE:-2}
      - RATE_LIMIT_API_REQUESTS_PER_MINUTE=${RATE_LIMIT_API_REQUESTS_PER_MINUTE:-50}
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:3000}
      - MAX_REQUEST_SIZE=${MAX_REQUEST_SIZE:-10485760}
      - MAX_FILES_COUNT=${MAX_FILES_COUNT:-6}
      - DEBUG_MODE=${DEBUG_MODE:-true}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/v1/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 30s
