services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL:-http://localhost:3000}
      - VITE_UPLOAD_TIMEOUT=${VITE_UPLOAD_TIMEOUT:-300000}
    volumes:
      - .:/app
    command: pnpm preview --host --port 5173

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${PORT:-3000}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - OPENROUTER_MODEL=${OPENROUTER_MODEL:-openai/gpt-4.1}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - MIN_QUIZ_LENGTH=${MIN_QUIZ_LENGTH:-5}
      - MAX_QUIZ_LENGTH=${MAX_QUIZ_LENGTH:-50}
      - ENABLE_RATE_LIMITING=${ENABLE_RATE_LIMITING:-true}
      - RATE_LIMIT_REQUESTS=${RATE_LIMIT_REQUESTS:-12}
      - RATE_LIMIT_WINDOW_MINUTES=${RATE_LIMIT_WINDOW_MINUTES:-1}
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:5173,http://localhost:3000}
      - AUTHORIZED_DOMAINS=${AUTHORIZED_DOMAINS:-http://localhost:5173}
      - MAX_REQUEST_SIZE=${MAX_REQUEST_SIZE:-10mb}
      - MAX_FILES_COUNT=${MAX_FILES_COUNT:-7}
      - DEBUG_MODE=${DEBUG_MODE:-true}
    volumes:
      - ./server:/app
    command: pnpm start

  # redis:
  #   image: redis:alpine
  #   ports:
  #     - "6379:6379"
